# -*- coding: utf-8 -*-
"""FonctionFibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gz6QBckxSSUo5w9hZbiQTgSqysH9dcY

**Exercice 3: Suite de Fibonacci**
"""

def fibonacci(n):
    v = [0,1]
    if n==1:
        print('0')
    elif n==2:
        print('[0,','1]')
    else:
        while(len(v) < n):
            v.append(0)
        if(n==0 or n==1):
            return 1
        else:
            v[0]=0
            v[1]=1
            for i in range(2,n):
                v[i]=v[i-1]+v[i-2]
            print(v)


n = int(input("Entrez un nombre:"))
print(fibonacci(6))

fibonacci(6)

