# -*- coding: utf-8 -*-
"""FonctionFactorielle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19_s1JbJAhZEsfpkSMc5vcv67yGCtd4n7

**Exercice 2: Fonction Factorielle**
"""

def factorielle(n):
    if (n == 0):
        return 1
    else:
        m = 1
        for i in range(2,n+1):
            m = m*i
        return m

factorielle(5)

